### PR TITLE
fixed var access for php 5.3 limitations

### PR DESCRIPTION
**Pull request by remi-san**

### CODE REVIEW

**Comment by oliviermadre** [comment]
what would u do on 5.5 ? Bind on closure ?

**Comment by SelrahcD** [comment]
Ok pour moi.

**Comment by remi-san** [comment]
What's the problem with 5.5?

Previous code didn't work because of properties accessibility rules which are more restrictive in 5.3.

In 5.4+, both work fine

**Comment by SelrahcD** [comment]
Delete ?

**Pull request merged**
