### PR TITLE
Adds utils dealing with League\Event

### PR DESCRIPTION
**Pull request by SelrahcD**

### CODE REVIEW

**Comment by ghost** [comment]
I'd really prefer if there was a serializer, but seems good nonetheless...

**Comment by SelrahcD** [comment]
What would be the advantage for a serializer ?

I would inclined to add it if the part with the json_en/decode is part of its job (as the test for SerializableEvent would be too) as anyone could use their own serialization system.

**Comment by ghost** [comment]
Yep, that would be a good benefit... but far from essential

**Comment by SelrahcD** [comment]
No serializer then ?

**Comment by ghost** [comment]
I'll let you decide

**Pull request merged**
